const LOG_ACTIONS = {
  // Auth
  LOGIN_SUCCESS:  'LOGIN_SUCCESS',
  LOGIN_FAILED:   'LOGIN_FAILED',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGOUT:         'LOGOUT',

  // Impersonation
  IMPERSONATE_START: 'IMPERSONATE_START',
  IMPERSONATE_END:   'IMPERSONATE_END',

  // Staff management
  STAFF_CREATED:            'STAFF_CREATED',
  STAFF_UPDATED:            'STAFF_UPDATED',
  STAFF_DELETED:            'STAFF_DELETED',
  PASSWORD_UPDATE_BY_OWNER: 'PASSWORD_UPDATE_BY_OWNER',

  // Products
  PRODUCT_CREATE:      'PRODUCT_CREATE',
  PRODUCT_UPDATE:      'PRODUCT_UPDATE',
  PRODUCT_DELETE:      'PRODUCT_DELETE',
  PRODUCT_BULK_IMPORT: 'PRODUCT_BULK_IMPORT',
  PRODUCT_GET_ALL:     'PRODUCT_GET_ALL',

  // Sales/Billing
  ORDER_CREATE:   'ORDER_CREATE',
  ORDER_GET_ALL:  'ORDER_GET_ALL',
  ORDER_UPDATE:   'ORDER_UPDATE',
  ORDER_DELETE:   'ORDER_DELETE',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',

  // Generic
  ERROR: 'ERROR',
};

module.exports = { LOG_ACTIONS };
