/**
 * Tooltip copy for the actions a new shop owner hesitates over.
 *
 * Kept in one place so the same action reads the same way wherever it appears
 * (Inventory toolbar, the sidebar, the onboarding journey, the help panel), and
 * so the wording can be reviewed as a set rather than hunted through JSX.
 *
 * HOUSE STYLE — every entry answers two questions, in this order:
 *   what does this button do, and why would I use it?
 * The "why" is the half that is usually missing, and it is the half a first-time
 * owner actually needs. Kept to roughly two short sentences: a tooltip that
 * needs scrolling is documentation in the wrong place.
 *
 * These describe the REAL behaviour of the real features. If a feature changes,
 * this copy is part of the change.
 */

export const TIPS = {
  // ── Inventory ───────────────────────────────────────────────────────────────
  export:
    'Downloads every product in this shop as a spreadsheet — with cost, price, '
    + 'stock, GST and the calculated profit and stock value, plus a totals row. '
    + 'Use it to check your catalogue in Excel, share it with your accountant, or '
    + 'keep a backup before a bulk edit.',

  exportXlsx:
    'Same data as the CSV, but as a formatted Excel workbook with a frozen header, '
    + 'currency formatting and live SUM totals. Choose this if you are opening it '
    + 'in Excel; choose CSV if you plan to edit it and import it back.',

  import:
    'Adds many products at once from a CSV file, into the shop you are viewing. '
    + 'Far faster than adding them one by one when you are setting up or received '
    + 'a new range. Every row is checked first and you see exactly what failed and why.',

  importSample:
    'Downloads a ready-made CSV in the exact format Import expects, filled with '
    + 'worked examples — including a colour/size variant row. Open it, replace the '
    + 'examples with your products, and upload it back. Start here if you are unsure '
    + 'about the columns.',

  scanBill:
    'Photograph or upload a supplier bill and the products on it are read out '
    + 'automatically, so you can add them without typing. You review and correct '
    + 'everything before anything is saved.',

  stockAudit:
    'Count your shelves and enter what you actually have. Any difference against '
    + 'the system is recorded as a dated adjustment with a reason, so shrinkage and '
    + 'miscounts are visible instead of silently wrong. Do this monthly — inaccurate '
    + 'stock makes your profit and tax figures wrong too.',

  // ── Billing ─────────────────────────────────────────────────────────────────
  billing:
    'The counter screen: pick products, take payment (cash, UPI, card or split) and '
    + 'print or share the invoice. Every completed bill reduces stock and feeds your '
    + 'sales, profit and GST figures automatically.',

  sampleBill:
    'Downloads a real example invoice — generated by the same code that prints your '
    + 'actual bills, with GST, a discount and payment details filled in. Use it to '
    + 'see the invoice layout, or to show your accountant the format, before you '
    + 'raise your first real bill.',

  holdBill:
    'Parks the current cart so you can serve someone else, then resume it later. '
    + 'Nothing is saved as a sale and no stock moves until you take payment.',

  // ── Reports & analysis ──────────────────────────────────────────────────────
  reports:
    'Your sales, best sellers, payment mix and profit and loss over any date range, '
    + 'built from your real bills. This is where you see whether the shop is actually '
    + 'making money, and which products are worth reordering.',

  taxProfit:
    'Works out your GST position and your taxable profit from real sales, purchases '
    + 'and expenses — showing the input tax credit you can legitimately claim and the '
    + 'deductions you may be missing. Nothing is hidden or altered; it shows what you '
    + 'already owe, accurately.',

  profitMargin:
    'Profit is what you keep after cost; margin is that profit as a percentage of the '
    + 'selling price. Watch the margin rather than the rupee figure — a high-turnover '
    + 'product on a thin margin can earn less than it appears to.',

  // ── Data hygiene ────────────────────────────────────────────────────────────
  lowStock:
    'Products at or below their reorder level. Check it before placing supplier '
    + 'orders so you do not run out of the lines that sell.',
};

/**
 * Short one-liners for tight spots (icon-only buttons, mobile toolbars) where the
 * full copy above would cover the screen.
 */
export const TIPS_SHORT = {
  export:       'Download all products as a spreadsheet, with totals',
  exportXlsx:   'Download as a formatted Excel workbook',
  import:       'Add many products at once from a CSV',
  importSample: 'Get a correctly formatted example CSV to fill in',
  scanBill:     'Read products off a supplier bill photo',
  stockAudit:   'Count shelves and record the differences',
  billing:      'Take payment and print an invoice',
  sampleBill:   'See an example invoice with GST filled in',
  reports:      'Sales, best sellers and profit & loss',
  taxProfit:    'GST position and taxable profit',
};
