import { useQuery }    from '@tanstack/react-query';
import { motion }      from 'framer-motion';
import {
  TrendingUp, ShoppingBag, Tag, Receipt,
  Download, Share2, X, BarChart2, Clock,
} from 'lucide-react';
import { reportsApi } from '../../api/sales.api';
import Modal           from '../Modal';

// ── Stat card ─────────────────────────────────────────────────────────────────
function StatCard({ icon: Icon, label, value, color = 'blue', sub }) {
  const colors = {
    blue:   'bg-blue-50 text-blue-600 ring-blue-200',
    green:  'bg-emerald-50 text-emerald-600 ring-emerald-200',
    purple: 'bg-purple-50 text-purple-600 ring-purple-200',
    orange: 'bg-orange-50 text-orange-600 ring-orange-200',
  };
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      className={`flex items-center gap-3 p-3.5 rounded-2xl ring-1 ${colors[color]}`}
    >
      <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${colors[color]}`}>
        <Icon className="w-4.5 h-4.5" style={{ width: '1.1rem', height: '1.1rem' }} />
      </div>
      <div className="min-w-0">
        <p className="text-[10px] font-bold uppercase tracking-wider opacity-60">{label}</p>
        <p className="text-lg font-black leading-tight tabular-nums">{value}</p>
        {sub && <p className="text-[10px] opacity-50 mt-0.5">{sub}</p>}
      </div>
    </motion.div>
  );
}

// ── Payment badge ─────────────────────────────────────────────────────────────
const PM_COLORS = {
  cash:   'bg-emerald-100 text-emerald-700',
  card:   'bg-violet-100  text-violet-700',
  upi:    'bg-orange-100  text-orange-700',
  credit: 'bg-amber-100   text-amber-700',
};

// ── Main modal ────────────────────────────────────────────────────────────────
export default function DailyClosingModal({ open, onClose, shopId }) {
  const today = new Date().toISOString().split('T')[0];

  const { data, isLoading } = useQuery({
    queryKey: ['daily-closing', shopId, today],
    queryFn:  () => reportsApi.dailyClosing({ shopId, date: today }),
    enabled:  open && !!shopId,
    staleTime: 60_000,
  });

  const d = data?.data || {};

  const handlePrint = () => {
    window.print();
  };

  const handleWhatsApp = () => {
    const lines = [
      `📊 *Daily Closing Summary*`,
      `📅 ${new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}`,
      ``,
      `💰 Revenue: ₹${(d.revenue || 0).toFixed(2)}`,
      `📈 Profit:  ₹${(d.profit  || 0).toFixed(2)}`,
      `🛍️ Orders:  ${d.orders || 0}`,
      d.topProduct ? `🏆 Top Product: ${d.topProduct.name} (${d.topProduct.qty} sold)` : '',
      ``,
      `_Generated by MultiShop POS_`,
    ].filter(Boolean).join('\n');

    window.open(`https://wa.me/?text=${encodeURIComponent(lines)}`, '_blank');
  };

  return (
    <Modal open={open} onClose={onClose} title="Daily Closing Summary" size="md">
      <div className="space-y-4">

        {/* Date header */}
        <div className="flex items-center gap-2 text-sm text-gray-500">
          <Clock className="w-4 h-4" />
          <span>
            {new Date().toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
          </span>
        </div>

        {isLoading ? (
          <div className="grid grid-cols-2 gap-3">
            {Array.from({ length: 4 }, (_, i) => (
              <div key={i} className="h-20 rounded-2xl bg-gray-100 animate-pulse" />
            ))}
          </div>
        ) : (
          <>
            {/* Stats grid */}
            <div className="grid grid-cols-2 gap-3">
              <StatCard
                icon={TrendingUp} label="Revenue" color="blue"
                value={`₹${(d.revenue || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`}
                sub={d.tax > 0 ? `incl. ₹${(d.tax || 0).toFixed(0)} tax` : undefined}
              />
              <StatCard
                icon={BarChart2} label="Profit" color="green"
                value={`₹${(d.profit || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`}
                sub={d.revenue > 0 ? `${Math.round((d.profit / d.revenue) * 100)}% margin` : undefined}
              />
              <StatCard
                icon={ShoppingBag} label="Orders" color="purple"
                value={String(d.orders || 0)}
                sub={d.orders > 0 ? `avg ₹${Math.round((d.revenue || 0) / d.orders)} / order` : undefined}
              />
              <StatCard
                icon={Tag} label="Discount Given" color="orange"
                value={`₹${(d.discount || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`}
              />
            </div>

            {/* Top product */}
            {d.topProduct && (
              <div className="flex items-center gap-3 px-4 py-3 bg-amber-50 border border-amber-200 rounded-2xl">
                <span className="text-xl">🏆</span>
                <div className="min-w-0">
                  <p className="text-xs font-bold text-amber-800 uppercase tracking-wide">Top Product</p>
                  <p className="font-bold text-gray-900 truncate">{d.topProduct.name}</p>
                  <p className="text-xs text-amber-700">
                    {d.topProduct.qty} sold &nbsp;·&nbsp; ₹{(d.topProduct.revenue || 0).toFixed(0)} revenue
                  </p>
                </div>
              </div>
            )}

            {/* Payment breakdown */}
            {d.paymentBreakdown?.length > 0 && (
              <div className="space-y-1.5">
                <p className="text-xs font-bold text-gray-400 uppercase tracking-wider">Payment Methods</p>
                <div className="flex flex-wrap gap-2">
                  {d.paymentBreakdown.map((pm) => (
                    <span key={pm._id}
                      className={`px-2.5 py-1 rounded-full text-xs font-bold capitalize ${PM_COLORS[pm._id] || 'bg-gray-100 text-gray-700'}`}>
                      {pm._id}: ₹{pm.total.toFixed(0)} ({pm.count})
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Empty state */}
            {!d.orders && (
              <div className="text-center py-8 text-gray-400">
                <Receipt className="w-10 h-10 mx-auto mb-2 opacity-30" />
                <p className="text-sm font-medium">No sales recorded today</p>
              </div>
            )}
          </>
        )}

        {/* Trust banner */}
        <div className="flex items-start gap-2 px-3 py-2 bg-blue-50 border border-blue-100 rounded-xl text-xs text-blue-700">
          <span className="text-base leading-none mt-0.5">🔐</span>
          <span>Your data is private and secure. We do not share your business data with any external authority.</span>
        </div>

        {/* Action buttons */}
        <div className="flex gap-2 pt-1">
          <button
            onClick={handlePrint}
            className="flex-1 flex items-center justify-center gap-2 h-10 border-2 border-gray-200 text-gray-700 rounded-xl text-sm font-semibold hover:bg-gray-50 transition"
          >
            <Download className="w-4 h-4" /> Print / PDF
          </button>
          <button
            onClick={handleWhatsApp}
            className="flex-1 flex items-center justify-center gap-2 h-10 bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl text-sm font-semibold transition"
          >
            <Share2 className="w-4 h-4" /> WhatsApp
          </button>
        </div>
      </div>
    </Modal>
  );
}
